# Generated by Django 4.2.5 on 2023-12-09 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_remove_ticket_id_alter_ticket_numero_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Timestamp de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Reservado', 'Reservado'), ('Cerrado', 'Cerrado')], default='Activo', max_length=15),
        ),
    ]
