# Generated by Django 4.2.5 on 2023-12-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_ticket_created_at_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
    ]
